### PR TITLE
Fixes for current rust-sdl2 library

### PR DESCRIPTION
**Pull request by Darkspear7**
I commented out the load texture ( from path ) functionality because I didn't find a way to create the texture without changes from the sdl2 library.

### CODE REVIEW

**Comment by xsleonard** [comment]
Whats the issue with `fn load_texture(&self, filename: &Path) -> SdlResult<Texture>`?

**Comment by Darkspear7** [comment]
From what I can tell it uses `ffi::IMG_LoadTexture` to get a pointer to a texture from C and I didn't find a way to build a `sdl2::render::Texture` object from a raw pointer.

**Comment by bombless** [comment]
I was thinking about transforming the texture to surface, and use `create_texture_from_surface` of `Renderer` to make a new texture. Don't know if this work, I don't know much about SDL2.
I guess it would be good to just add a unsafe from_raw() to Renderer.
cc  @AngryLawyer @nukep

**Comment by bombless** [comment]
Errr... can we use `RenderTarget` and its `get()` to obtain a texture?
Sorry I have some other things to do, I'll try if this works.

**Comment by Darkspear7** [comment]
You use RenderTarget when you want to render your image on a texture for things like deffered rendering. I think the best thing would be, as you suggested, to implement a `from_ll` for `Texture`.

**Comment by nukep** [comment]
I'm all for adding a `from_ll` to `Texture`, as long as it's marked `unsafe` and the lifetime is inferred:
```rust
pub unsafe fn from_ll<'r>(raw: *const ll::SDL_Texture, owned: bool) -> Texture<'r> {...}
```

**Comment by KevinBalz** [comment]
+1 Changes work for me

**Comment by KevinBalz** [comment]
+1 Works fine, please merge

**Comment by alexandercampbell** [comment]
+1, have been using this locally without issues

**Comment by jaburns** [comment]
+1 Is this repository still active? rust-sdl2 is continuing development and this repo is decaying against it.  There are more changes required now on top of this PR to build and run the demo.

**Comment by AngryLawyer** [comment]
Didn't realise xsleonard fell off the planet. I've merged a fixing PR and published to Cargo.

**Pull request closed without merging**
