### PR TITLE
Fix building issues with rust version >= 1.6

### PR DESCRIPTION
**Pull request by NotKild**

### CODE REVIEW

**Comment by petevine** [comment]
@NotKild 
Could you squash these commits into one?

**Comment by NotKild** [comment]
Yup here it is

**Comment by petevine** [comment]
The title should read >= 1.6

@xsleonard

This is the correct fix, please merge.

**Comment by NotKild** [comment]
OK thanks

**Comment by xsleonard** [comment]
Needs to be rebased on master

**Comment by NotKild** [comment]
ok i will do that

**Comment by NotKild** [comment]
@xsleonard Done

**Pull request merged**
